modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL = "https://github.com/alec016/DegrassiConf/issues"
[[mods]]
modId = "degrassiconf"
version = "${version}"
displayName = "Degrassi Conf"
logoFile = "icon.png"
description = '''

'''
[[dependencies.degrassiconf]]
modId = "forge"
# Does this dependency have to exist - if not, ordering below must be specified
mandatory = true
# The version range of the dependency
versionRange = "[43,)"
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering = "NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side = "BOTH"

[[dependencies.degrassiconf]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.degrassiconf]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "NONE"
side = "BOTH"
